# Copyright 2010 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test dwarf4 signatured types.

set test "dw4-sig-types"
set executable ${test}.x

# This test is intended for targets which support DWARF-4.
# Since we pass an explicit -gdwarf-4 to the compiler, we let
# that be the test of whether the target supports it.

if {[build_executable ${test}.exp ${executable} \
	 {dw4-sig-types.cc dw4-sig-types-b.cc} \
	 {debug c++ additional_flags=-gdwarf-4}] == -1} {
    return -1
}

# GOOGLE LOCAL: v12 generates bad headers for TUs, gdb throws an error causing
# dejagnu to issue an ERROR, which we don't want in the nightly test runs.
# NOTE: build_executable calls get_compiler_info, which we need for
# test_compiler_info.
# This must be done before starting gdb (ergo the need to call build_executable
# and clean_restart separately, instead of just calling prepare_for_testing).
if {[test_compiler_info {gcc-4-[0-3]-*}]} {
    return -1
}

clean_restart $executable

# Stress test gdb's handling of cached comp units, disable the cache.
gdb_test_no_output "maint set dwarf2 max-cache-age 0"

if ![runto_main] {
    return -1
}

# Bring symtab for myset into gdb.
gdb_test "p myset" ".*"

# This is enough to trigger the problem in PR 11942.
gdb_breakpoint "foo"
gdb_continue "foo"
